BE-38 implement crawler for referaty
P3K-TEAM/scripts pull request #1
Opened 2020-11-15 20:37 UTC by Hemii

2020-11-15 21:42 UTC, MCFreddie777 commented
Please don't forget to freeze the pip packages into requirements text file.

2020-11-19 18:53 UTC, MaliniakovaKarin approved these changes

2020-11-19 18:58 UTC, MCFreddie777 requested changes
Reviewed, left some comments.

2020-11-19 18:58 UTC, MCFreddie777 commented on .gitignore
> +.idea
Newline :D

2020-11-19 18:58 UTC, MCFreddie777 commented on src/crawler_referaty/requirements.txt
> +six==1.15.0
I cannot find scrappy in the dependencies.

2020-11-19 18:58 UTC, MCFreddie777 commented on src/crawler_referaty/scraper.py
> +    output_file = open(os.path.join(dirname,'../../data/referaty.json'), 'a+', encoding='utf8' )
So it worked here, and did not in other python scripts? :trollface:

2020-11-19 18:58 UTC, MCFreddie777 commented on src/crawler_referaty/scraper.py
> +    def start_requests(self):
Duplicate method, please remove.

2020-11-19 18:58 UTC, MCFreddie777 commented on src/crawler_referaty/scraper.py
> +
Missing newline :smile:

2020-11-19 18:58 UTC, MCFreddie777 commented on src/crawler_referaty/scraper.py
> +
Unnecessary whitespace.

2020-11-19 21:14 UTC, MCFreddie777 approved these changes
Good work. 🐝

2020-11-19 21:14 UTC, merged